name: Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get code
  #       uses: actions/checkout@v4

  #     - name: Install deps
  #       run: yarn install

  #     - name: Cache deps
  #       uses: actions/cache@v4
  #       with:
  #         path: ~/.npm
  #         key: node-modules-${{ hashFiles('**/yarn.lock') }}

  #     - name: Run linter
  #       run: yarn lint

  deploy:
    runs-on: ubuntu-latest
    # needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check Node.js and PM2 versions
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          echo user name
          who
          echo node version
          node -v
          echo yarn version
          yarn -v
          echo pm2 version
          pm2 -v
          EOF

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/nardo/dd
          git pull origin main
          cat /etc/home/nardo/dd/ecosystemConfig.json
          yarn install
          yarn build
          pm2 delete dd || true  # Игнорировать ошибку, если процесс не существует
          pm2 start /etc/home/nardo/dd/ecosystemConfig.json
          EOF
