name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pm2 stop dd || true
            cd /home/nardo/dd
            nvm use 20.18.0
            node -v
            git pull
            yarn install
            yarn build
            pm2 restart ecosystem.config.json || pm2 start ecosystem.config.json
