name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          yarn install
          yarn build

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: |
            .next/
            public/
            package.json
            yarn.lock
            ecosystem.config.js

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./production-files

      - name: Copy production files to server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./production-files/*
          target: /home/nardo/dd/production

      - name: SSH command to update and restart app
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/nardo/dd/production
            yarn install --production
            pm2 restart ecosystem.config.js --env production || pm2 start ecosystem.config.js --env production
