name: Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install deps
        run: yarn install

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/.npm # Путь, где будут храниться пакеты
          key: node-modules-${{ hashFiles('**/yarn.lock') }} # Задаем ключ

      - name: Run linter
        run: yarn lint
  deploy:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/nardo/dd
          git pull origin main
          yarn install
          yarn build
          pm2 delete dd
          pm2 start ./ecosystemConfig.json
          EOF
